services:
  postgres:
    image: postgres:15
    container_name: clipboard_postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - clipboard_network
    restart: unless-stopped

  ai-service:
    build: ./ai-service
    container_name: clipboard_ai
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEM_ID=${GEM_ID}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ENHANCED_AI_SERVICE_URL=${ENHANCED_AI_SERVICE_URL}
      - USE_ENHANCED_AI=${USE_ENHANCED_AI}
      - FALLBACK_TO_LOCAL_AI=${FALLBACK_TO_LOCAL_AI}
      - LOCAL_AI_TIMEOUT=${LOCAL_AI_TIMEOUT}
      - WSL_HOST=${WSL_HOST}
      - REMOTE_CLIENT_HOST=${REMOTE_CLIENT_HOST}
    depends_on:
      - postgres
    networks:
      - clipboard_network
    restart: unless-stopped

  tts-service:
    build: ./tts-service
    container_name: clipboard_tts
    environment:
      - GOOGLE_TTS_KEY=${GOOGLE_TTS_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/google-service-account.json
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./web-app/public/mp3:/app/public/mp3
      - ./gen-lang-client-0899352753-bf1b34113193.json:/app/config/google-service-account.json:ro
    depends_on:
      - postgres
    networks:
      - clipboard_network
    restart: unless-stopped

  web-app:
    build: ./web-app
    container_name: clipboard_web
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=3000
      - ENHANCED_AI_SERVICE_URL=${ENHANCED_AI_SERVICE_URL}
      - USE_ENHANCED_AI=${USE_ENHANCED_AI}
      - FALLBACK_TO_LOCAL_AI=${FALLBACK_TO_LOCAL_AI}
      - WSL_HOST=${WSL_HOST}
      - REMOTE_CLIENT_HOST=${REMOTE_CLIENT_HOST}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    expose:
      - "3000"
    volumes:
      - ./web-app/public/mp3:/app/public/mp3
    depends_on:
      - postgres
    networks:
      - clipboard_network
    restart: unless-stopped

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: clipboard_proxy
    ports:
      - '80:80'
      - '443:443'
      - '81:81'  # Admin UI
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
      - DISABLE_IPV6=true
      - CERT_MAIL=${CERT_MAIL}
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - web-app
    networks:
      - clipboard_network
    restart: unless-stopped

volumes:
  postgres_data:
  npm_data:
  npm_letsencrypt:

networks:
  clipboard_network:
    driver: bridge 